library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2);
library(ggthemes)
library(imager)
library(reshape2)
library(cowplot)
library(latex2exp)
library(ggsci)
library(gg3D)
library(plot3D)
np = reticulate::import("numpy")